name: bin test

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - feature/gh-action
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACT_GHPROJ: nektos/act
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Detect Latest
        id: version
        env:
          ACT_APIROOT: "https://api.github.com/repos/${{ env.ACT_GHPROJ }}"
          ACT_DWROOT: "https://github.com/${{ env.ACT_GHPROJ }}/releases/download"
        run: |
          printf '::set-output name=version::%s\n' \
            "$( wget -q -O - "${{ env.ACT_APIROOT }}/releases" |
                grep -oE '[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"v([0-9]+\.[0-9]+)"' |
                sed -E 's/[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"v([0-9]+\.[0-9]+)"/\1/' |
                head -n 1)"
      -
        name: Install
        uses: ./
        env:
          ACT_DWROOT: "https://github.com/${{ env.ACT_GHPROJ }}/releases/download"
        with:
          installer: tar
          extract: act
          url: ${{ env.ACT_DWROOT }}/v${{ steps.version.outputs.version }}/act_Linux_x86_64.tar.gz

      - name: Test
        run: act --version
